import "./globals.css";
import type { Metadata } from "next";
import Navigation from "./components/helpers/Navigation";

export const metadata: Metadata = {
  title: "E-commerce app | Home",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <Navigation />

        {children}
      </body>
    </html>
  );
};

export default RootLayout;
